spring:
  application:
    name: evaluation-backend
  profiles:
    active: Local
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: com.nicico.copper.common.hibernate.CustomOracleDialect
        hbm2ddl:
          schema_filter_provider: com.nicico.copper.common.hibernate.CustomSchemaFilterProvider
    open-in-view: false
  liquibase:
    database-change-log-table: Z_LIQ_CHANGELOG
    database-change-log-lock-table: Z_LIQ_CHANGELOG_LOCK
    change-log: classpath:/db/changelog-master.xml
    enabled: false
  main:
    allow-bean-definition-overriding: true
  activiti:
    rest-api-enabled: true
    history-level: full
    database-schema-update: true
    db-history-used: true
  redis:
    port: 6379
  servlet:
    multipart:
      max-file-size: 1000MB

server:
  port: 8080
  servlet:
    context-path: /evaluation-backend
    session:
      cookie:
        name: App_${spring.application.name}

management:
  endpoint:
    health:
      show-details: always

nicico:
  jpa:
    entity:
      package: com.nicico.evaluation-backend
  google:
    mail:
      username:
      password:
  mail:
    domain:
    url:
    username:
    password:
  upload:
    dir: /var/nicico/${spring.application.name}/
  workflow:
    update:
      mode: true
  bpmn:
    upload:
      dir: /var/nicico/${spring.application.name}/
#  security:
#    sys-password: password
---
logging :
  level:
   liquibase : INFO
