spring:
  datasource:
    url: jdbc:oracle:thin:@//172.16.180.49:1521/pdb_dev
    username: dev_evaluation
    password: devevaluation
  redis:
    host: devapp01.icico.net.ir
    password: nicico
  security:
    oauth2:
      client:
        registration:
          oserver:
            client-id: ${spring.application.name}
            client-secret: password
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          oserver:
            authorization-uri: http://devapp01.icico.net.ir/oauth/authorize
            token-uri-swagger: http://devapp01.icico.net.ir/oauth/token
            token-uri: http://devapp01.icico.net.ir/oauth/token
            user-info-uri: http://devapp01.icico.net.ir/user/info
            user-name-attribute: username
  cache:
    jcache:
      config: classpath:ehcache.xml
  config:
    activate:
      on-profile: Development
nicico:
  server:
    url: http://devapp01.icico.net.ir/evaluation-backend
  security:
    sys-password: password
  hrmClient: 'http://devapp01.icico.net.ir/hrm/api/v1'
  hrmBackend: 'http://devapp01.icico.net.ir/hrm-backend/api/v1'
  oauthBackend: 'http://devapp01.icico.net.ir/api'
  hrm-password: password

  upload:
    dir: /var/nicico/${spring.application.name}/upload

ui:
  redirect:
    #address: http://devapp01.icico.net.ir/evaluation-frontend/auth-redirect
    address: http://devapp01.icico.net.ir/evaluation-frontend

  landing:
    address: http://devapp01.icico.net.ir/evaluation-backend
    #address: http://172.16.6.196:4200

    fmsGroupId: '6450d6e2a2bda66902a00ffe'
    fmsUrl: 'http://devapp01.icico.net.ir/fms/file'



