spring:
  datasource:
    url: jdbc:oracle:thin:@//172.16.180.49:1521/pdb_stg
    username: stg_evaluation
    password: stgevaluation
  redis:
    host: redis
    password: nicico
  security:
    oauth2:
      client:
        registration:
          oserver:
            client-id: ${spring.application.name}
            client-secret: password
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: user_info
        provider:
          oserver:
            authorization-uri: http://staging.icico.net.ir/oauth/authorize
            token-uri: http://staging.icico.net.ir/oauth/token
            user-info-uri: http://staging.icico.net.ir/user/info
            token-uri-swagger: http://staging.icico.net.ir/oauth/token
            user-name-attribute: username
nicico:
  hrmClient: 'http://staging.icico.net.ir/hrm/api/v1'
  upload:
    dir: /var/nicico/${spring.application.name}/
ui:
  redirect:
    address: http://staging.icico.net.ir/evaluation-frontend/auth-redirect

  landing:
    address: http://staging.icico.net.ir/evaluation-frontend

    fmsGroupId: '6450ce9763a9bb68f5df2dd9'
    fmsUrl: 'http://storage.icico.net.ir/fms/file'